/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
    if (n <= 1) 
    return false;
    for (long i = 2; i <= Math.sqrt(n); i++) {
        if (n % i == 0) 
            return false;
    }

    return true;
}
    
    public long firstPrimeNumberIn(String n) {
        for ( int i = 0; i < n.length(); i++){
            String s = n.substring(i,i+1);
            long num = Long.parseLong(s);
        if (isPrime(num)){
            return num;

        }
        }
        return -1;
    }
}
